### PR TITLE
Get response comments from DataStore (new PR as the last one got automatically merged)

### PR DESCRIPTION
**Pull request by AymarMuhikira**
-modify doGet to interact with DataStore

### CODE REVIEW

**Comment by gbuenoandrade** [comment]
Which one got automatically merged?

**Comment by AymarMuhikira** [comment]
> -modify doGet to interact with DataStore

The [pull request #8](https://github.com/AymarMuhikira/step-projects/pull/8) was automatically merged

**Comment by antmar** [comment]
Please submit previous (approved) PRs and update this PR so there are no merge conflicts.

**Comment by gbuenoandrade** [comment]
> Please submit previous (approved) PRs and update this PR so there are no merge conflicts.

Please address the comments in https://github.com/AymarMuhikira/step-projects/pull/9 and merge that first.

**Pull request closed without merging**
